# Generated by Django 4.2.25 on 2025-11-01 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brain_start', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EEGDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='时间')),
                ('delta', models.IntegerField(default=0, verbose_name='Delta波')),
                ('theta', models.IntegerField(default=0, verbose_name='Theta波')),
                ('low_alpha', models.IntegerField(default=0, verbose_name='低Alpha波')),
                ('low_beta', models.IntegerField(default=0, verbose_name='Low Beta波')),
                ('low_gamma', models.IntegerField(default=0, verbose_name='Low Gamma波')),
                ('high_alpha', models.IntegerField(default=0, verbose_name='High Alpha波')),
                ('high_beta', models.IntegerField(default=0, verbose_name='High Beta波')),
                ('high_gamma', models.IntegerField(default=0, verbose_name='High Gamma波')),
                ('attention', models.IntegerField(default=0, verbose_name='注意力')),
                ('meditation', models.IntegerField(default=0, verbose_name='冥想')),
                ('signal_quality', models.IntegerField(default=0, verbose_name='信号质量')),
            ],
            options={
                'verbose_name': '脑电有效数据点',
                'verbose_name_plural': '脑电有效数据点',
                'db_table': 'eeg_data_point',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='EEGRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_id', models.CharField(max_length=255, unique=True, verbose_name='记录ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('name', models.CharField(default='EEG_Recording', max_length=255, verbose_name='记录名称')),
                ('description', models.TextField(verbose_name='描述')),
                ('data_count', models.BigIntegerField(default=0, verbose_name='数据点数量')),
            ],
            options={
                'verbose_name': '脑电有效记录',
                'verbose_name_plural': '脑电有效记录',
                'db_table': 'eeg_record',
                'ordering': ['-start_time'],
            },
        ),
        migrations.DeleteModel(
            name='BrainData',
        ),
        migrations.AddField(
            model_name='eegdatapoint',
            name='recording',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='brain_start.eegrecord'),
        ),
    ]
