# Generated by Django 4.2.25 on 2025-11-08 14:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('brain_start', '0002_eegdatapoint_eegrecord_delete_braindata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eegrecord',
            name='recording_id',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='记录ID'),
        ),
    ]
